### ISSUE TITLE
REVERSE_VIDEO token in the .g4 is spelled out as RESERVE-VIDEO, should be REVERSE-VIDEO

### ISSUE THREAD

**Issue by wfahle** [uwol/proleap-cobol-parser#102]
The REVERSE_VIDEO definition reads:
REVERSE_VIDEO : R E S E R V E MINUSCHAR V I D E O;
Should be:
REVERSE_VIDEO : R E V E R S E MINUSCHAR V I D E O;

In other words, reverse the S and the V in the right-hand string.

**Comment by uwol** [comment]
😃 thanks for reporting the issue. Fixed on main.
