### ISSUE TITLE
C/C++ examples

### ISSUE THREAD

**Issue by mbsteixeira** [uwol/proleap-cobol-parser#76]
It is not a issue.
I would like to know if there are any examples implemented in C / C ++. I need to implement a cobol program analyzer and C / C ++ is my development environment.

**Comment by uwol** [comment]
Hi, there is no implementation in C/C++. The ANTLR grammar files probably could be used to generate C/C++ code, but those lines would only make 5% of the parser. I would strongly suggest to use Java here.

**Comment by mbsteixeira** [comment]
Thanks!
