### ISSUE TITLE
Package io.proleap.cobol.Cobol85Parser does not exist.

### ISSUE THREAD

**Issue by lyingd** [uwol/proleap-cobol-parser#79]
Hi there, package io.proleap.cobol.Cobol85Parser does not exist, where can I find it?

**Comment by uwol** [comment]
Hi lyingd,

you can parse COBOL code with `io.proleap.cobol.asg.runner.impl.CobolParserRunnerImpl.analyzeFile` and `io.proleap.cobol.asg.runner.impl.CobolParserRunnerImpl.analyzeCode` as documented in README.md. 

The internal ANTLR parser class can be found at `io.proleap.cobol.CobolParser`. This class is generated by ANTLR from `src/main/antlr4/io/proleap/cobol/Cobol.g4` when running `mvn clean package` or simply importing the project as Maven project into Eclipse.

Best regards,
Ulrich

**Comment by lyingd** [comment]
It work! Thanks Ulrich!
