### ISSUE TITLE
Can't find CobolLexer class while building the project

### ISSUE THREAD

**Issue by jeffersonlsz** [uwol/proleap-cobol-parser#82]
Hi all,

I'm trying to build the project just as the README describes but it just can't find the class 'CobolLexer.java'.

Here is a list with the occurences mentioned by the Eclipse IDE. I also searched for it in the repository but I had no success. 
How do I manage to build that project ? 

CobolParseTestRunnerImpl.java	/proleap-cobol-parser-master/src/test/java/io/proleap/cobol/runner/impl	line 77	
CobolParseTestRunnerImpl.java	/proleap-cobol-parser-master/src/test/java/io/proleap/cobol/runner/impl	line 77	
CobolParseTestRunnerImpl.java	/proleap-cobol-parser-master/src/test/java/io/proleap/cobol/runner/impl	line 25	
TestGenerator.java	/proleap-cobol-parser-master/src/test/java/io/proleap/cobol
TestGenerator.java	/proleap-cobol-parser-master/src/test/java/io/proleap/cobol	
CobolParserRunnerImpl.java	/proleap-cobol-parser-master/src/main/java/io/proleap/cobol/asg/runner/impl	line 206	
CobolParserRunnerImpl.java	/proleap-cobol-parser-master/src/main/java/io/proleap/cobol/asg/runner/impl	line 206	
CobolParserRunnerImpl.java	/proleap-cobol-parser-master/src/main/java/io/proleap/cobol/asg/runner/impl	line 23

**Comment by jeffersonlsz** [comment]
I solved the issue. 

I just deleted the 'target' maven generated directory manually and ran the command 'mvn clean package' again and it compiled fine.

**Comment by uwol** [comment]
Perfect, thanks for letting me know. Simply running `mvn clean package` normally should suffice, so that the Maven ANTLR plugin kicks in and generates the ANTLR parser code from the ANTLR COBOL grammar files.
